### ISSUE TITLE
Идеи/проблемы на обновление v3.4

### ISSUE THREAD

**Issue by GyverLibs** [GyverLibs/GyverPortal#52]
### CHANGELOG v3.4
- Добавлено
  - HTML Canvas (рисование в браузере) + обновление из скетча + Processing API
  - Разметка страницы в стиле панели управления с боковым меню, компоненты UI_BEGIN, UI_MENU, UI_BODY, UI_END, UI_LINK
  - UPDATE_CLICK() - вызывает update у указанных компонентов при клике по указанным компонентам
  - OTA.error() для вывода текста ошибки в любое место на странице
  - EVAL() выполнение отправленного в update js кода
  - GyverPortal::setFS()
  - Выбор цвета для иконок, FILE_UPLOAD, FOLDER_UPLOAD, OTA_FIRMWARE, OTA_FILESYSTEM, TITLE, LABEL, SPAN, PLAIN, BOLD и HR
  - Макс. ширина для GRID
  - JS_BEGIN() и JS_END()
  - В BUILD_BEGIN_FILE() и BUILD_BEGIN() можно передать тему оформления
  - PAGE_TITLE() - смена имени вкладки в браузере, в т.ч. по update
  - Цвет GP_WHITE
  - Иконки-кнопки ICON_BUTTON() и ICON_FILE_BUTTON()
  - ONLINE_CHECK() - отображение состояния соединения с esp
  - Подписи к осям AJAX_PLOT
  - GyverPortal::caching(bool), GyverPortal::clearCache()
  - Обработка удержания кнопок, отдельный обработчик hold()
- Исправлено
  - Мелкие баги
  - HINT() для BUTTON, SWITCH и UPLOAD
  - Потенциальный баг в механизме update
  - ICON_FILE()
- Улучшено
  - COLOR теперь можно парсить как int
  - Значительно ускорена (кеширование) загрузка страницы без скриптов/стилей в spiffs
  - При обновлении библиотеки не нужно чистить кеш браузера
  - FILE_MANAGER(): удаление файлов теперь не меняет url в браузере + добавлены кнопки скачать и переименовать + выбор директории
  - Улучшена обработка отпускания кнопки
  - SPINNER(): удержание кнопок, настройка скорости в GP.setSpinnerPeriod()
  - Убран перенос строки в последней строке в LOG
- Изменено
  - Логика работы всплывающих окон, УБРАН АРГУМЕНТ ПЕРИОД!
  - SPINNER(): убрана ширина, сделана автоширина, значение по центру
  - Автоматическое скачивание/загрузка/удаление/переименование ТЕПЕРЬ ВКЛЮЧЕНО ПО УМОЛЧАНИЮ!
  - Отсортированы примеры, portal переименован в ui для краткости
  - clickUp и clickDown вынесены в обработчик hold()

### TODO
- Настройка цвета у check
- button_n
- таблицы TH 
- NUMBER min max

### v3.5
- вебсокет

### Лажа
- Переделать иконки на otf https://fontawesome.com/search?o=r&m=free&s=solid&f=classic
```css
@font-face {
    font-family: 'icons_otf';
    src: url('/font.ttf');
}
.fa_icon {
    font-family: 'icons_otf';
}
```

### Осмыслить
- ОТА через cmd/shell `curl -vF firmware=@firmware.bin http://x.x.x.х/GP_OTAupload`
- Кастом чекбокс
```css
.custom-checkbox>input{position:absolute;opacity:0;display:none;}
.custom-checkbox>span::before{content:'';border-radius:8px;padding:4px 12px;color:#bbb;background-color:#fff;border:1px solid #adb5bd;border-radius:0.25em;transition:.1s;cursor:pointer;}
.custom-checkbox>input:checked+span::before{border-color:#4CAF50;background-color:#4CAF50;background-image:url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath d='m12.82,3l-6.6,6.6l-3,-3-1.9,1.9l5,5.00687l8.5,-8.5-1.9,-1.9z' fill='%23fff'/%3e%3c/svg%3e");}
.custom-checkbox>input:disabled+span::before{background-color:#e9ecef;}
.custom-checkbox>input:hover+span::before{filter:brightness(0.85);}
```
