### ISSUE TITLE
Вложенные блоки отображаются неверно

### ISSUE THREAD

**Issue by lgadina** [GyverLibs/GyverPortal#89]
В хроме/яндексбраузере 
![image](https://github.com/GyverLibs/GyverPortal/assets/370763/a245ddb1-592b-4c93-8f0d-2e53bef1264a)

код:
```c
M_GRID(
      M_BLOCK_THIN_TAB(
          "Котел",
          M_BLOCK_THIN_TAB(
              "Отопление",
              M_BOX(GP.LABEL("Темп. прямой"); GP.LABEL("30", "t_in"););
              M_BOX(GP.LABEL("Темп. обратн"); GP.LABEL("22", "t_out");););
          M_BLOCK_THIN_TAB(
              "Горячая вода",
              M_BOX(GP.LABEL("Темп. хол."); GP.LABEL("23", "t_cold"););
              M_BOX(GP.LABEL("Темп. гор."); GP.LABEL("24", "t_hot");););
          M_BOX(GP.LABEL("Нагрев вкл"); GP.LED("boilerOn", false););););
  M_GRID(
      M_BLOCK_THIN_TAB(
          "UPS",
          M_BOX(GP.LABEL("Вход"); GP.NUMBER("v_in", "", 221););
          M_BOX(GP.LABEL("Выход"); GP.NUMBER("v_out", "", 220););););
```

**Comment by XRay3D** [comment]
В стиле 
```css
#grid .block {
  width: 100%;  <= заменить
  flex: auto;   <= на это
  margin: 10px;
}
```
и в начало добавить 
```css
* {
  box-sizing: border-box;
}
```
https://github.com/XRay3D/GyverPortal/blob/dev/Test/DARK.css
